### ISSUE TITLE
Migrate from AniList API v1 to API v2

### ISSUE THREAD

**Issue by matchai** [Nihilate/Roboragi#10]
AniList API v2 has been released for a few months now, deprecating API v1. The plan is to officially end support for its existing REST API v1 by May 2018, in favor of the new GraphQL API.

Here is a link to the docs for migrating from API v1 to v2:
https://anilist.gitbooks.io/anilist-apiv2-docs/migrating-from-apiv1.html

**Comment by Nihilate** [comment]
Oh shit, thanks for reminding me! I've already half done it, but forgot and never finished it off haha

**Comment by Nihilate** [comment]
This has been done (and it's looks like the migration is pretty smooth so far). Thanks again for the reminder!
