### ISSUE TITLE
[Feature] Ignore anything in side of `` (code block)

### ISSUE THREAD

**Issue by chiefnoah** [Nihilate/Roboragi#2]
Responded to some XML I posted in a comment [here](https://www.reddit.com/r/awwnime/comments/3ggakw/toshino_kyouko_sketch_yuruyuri/cty6x05). The bots comment was removed by the mods.

**Comment by Nihilate** [comment]
The issue is that the bot currently requires the pointed braces (<>) to look for manga. I've posted some possible solutions in the [thread you posted on the subreddit](https://www.reddit.com/r/Roboragi/comments/3ghp0s/issue/).
