### ISSUE TITLE
Add a code coverage report to the CI pipeline

### ISSUE THREAD

**Issue by Nihilate** [Nihilate/Roboragi#53]
It would be worth adding a code coverage checker to the CI pipeline. Given coverage is so low at the moment, it might be difficult to enable it to fail a build, but I'll investigate some options (maybe to only check new code, or to make sure it doesn't go backwards with a threshold).

**Comment by reillysiemens** [comment]
Since we already have tests using [pytest](https://pypi.org/project/pytest/) I'd recommend we use [pytest-cov](https://pypi.org/project/pytest-cov/). It's worked quite nicely for me in my own projects and I know it at least plays well with TravisCI/[Coveralls](https://coveralls.io/).

**Comment by Nihilate** [comment]
Perfect, that's what I was looking into using as well :)
