### ISSUE TITLE
[Feature] Shikimori support

### ISSUE THREAD

**Issue by MrModest** [Nihilate/Roboragi#59]
Can you add support for Shikimori.org link?
It have same id with MAL. 

## Example.

Shiki: https://shikimori.org/animes/37991
MAL: https://myanimelist.net/anime/37991

Also it have open API (if needed):
https://shikimori.org/api/doc/1.0
https://shikimori.org/api/doc

**Comment by Nihilate** [comment]
Thanks for the expression of interest, but as Reddit and Roboragi's direct users are nearly entirely English-speaking, I have no plans to add non-English data sources. Sorry for the inconvenience.
