### ISSUE TITLE
Kitsu.io

### ISSUE THREAD

**Issue by qwerzy** [Nihilate/Roboragi#9]
It's the new hummingbird yet it doesn't get linked to, thoughts?

**Comment by Nihilate** [comment]
[Kitsu.io was added like 6 months ago.](https://github.com/Nihilate/Roboragi/blob/master/roboragi/Kitsu.py) [Here it is in action.](https://www.reddit.com/r/Animesuggest/comments/7wc76b/looking_for_anime_that_is_like_ngnl_or_problem/dtz7a76/)
